# This is a basic workflow to help you get started with Actions

name: "Deploy vue application to github pages with gh-pages"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel aa
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build        
      - name: Push changes
        uses:  mariogb/actionvuelon@master
        with: 
          username: mariogb
          reponame: vuelon
          token: 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
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
